services:
  app:
    container_name: zenmonk-website-app
    image: zenmonk-website:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: "no"
    ports:
      - "${APP_FORWARD_PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
    networks:
      - zenmonk-website-network

  mailpit:
    container_name: zenmonk-website-mailpit
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "${MAIL_FORWARD_PORT:-1026}:1025"
      - "${MAIL_WEB_UI_FORWARD_PORT:-8026}:8025"
    networks:
      - zenmonk-website-network
    volumes:
      - mailpit_data:/data
    environment:
      MP_DATABASE: ${MAIL_STORAGE_PATH:-/data/mailpit.db}

networks:
  zenmonk-website-network:
    driver: bridge

volumes:
  mailpit_data:
    driver: local

