name: zenmonk-website

services:
  app:
    container_name: zenmonk-website-app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${APP_FORWARD_PORT:-80}:${PORT:-3000}"
    env_file:
      - .env
    networks:
      - zenmonk-website-network

  # mailhog:
  #   container_name: zenmonk-website-mailhog
  #   image: 'mailhog/mailhog:v1.0.1'
  #   restart: unless-stopped
  #   ports:
  #     - "${MAIL_FORWARD_PORT:-1026}:1025"
  #     - "${MAIL_WEB_UI_FORWARD_PORT:-8026}:8025"
  #   networks:
  #     - zenmonk-website-network

  mailpit:
    container_name: zenmonk-website-mailpit
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "${MAIL_FORWARD_PORT:-1026}:1025"
      - "${MAIL_WEB_UI_FORWARD_PORT:-8026}:8025"
    networks:
      - zenmonk-website-network
    volumes:
      - mailpit_data:/data
    environment:
      MP_DATA_FILE: ${MAIL_STORAGE_PATH:-/data/mailpit.db}

networks:
  zenmonk-website-network:
    driver: bridge

volumes:
  mailpit_data:
    driver: local
