import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Zenmonk | Technology Center',
  description: 'Generated by create next app',
}

export default function RouteLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      {children}
    </>
  )
}
