import type { Metadata } from 'next'
import { Poppins, Montserrat, Inter } from 'next/font/google'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import CustomLoader from '@/modules/loader'
import { Footer } from '@/shared/footer-section'
import Header from '@/shared/header'
import SmoothScroller from '@/shared/scroll-smoother'
import ScrollProvider from '@/shared/scroll-smoother/scroll-provider'

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
})

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Zenmonk | Technology Center',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={inter.className}>
      <body className={` ${poppins.variable} ${montserrat.variable}`}>
        <AppRouterCacheProvider>
          <ScrollProvider>
            <Header />
            <CustomLoader />
            <SmoothScroller>
              {children}
              <Footer />
            </SmoothScroller>
          </ScrollProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
