import type { Metadata } from "next";
import { Inter, Poppins, Montserrat } from "next/font/google";
import Header from "@/shared/header";
import "./globals.css";
import { Footer } from "@/modules/home/sections";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Zenmonk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="cVxgSbwIF1EFnQkz6O2sd_gNVO8dskUUoYSfwaEQWPE"
        />
      </head>

      <body
        className={`${inter.variable} ${poppins.variable} ${montserrat.variable}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
